import { supabaseBrowser } from './supabase/browser';

export function handleSupabaseError(error: string): string {
  const errorMessages: { [code: string]: string } = {
    '22001': 'El valor ingresado est치 fuera del rango permitido',
    '23502': 'Por favor, completa todos los campos obligatorios',
    '23505': 'El valor ingresado ya existe, por favor ingresa uno diferente',
    '42501': 'No tienes permisos para realizar esta operaci칩n',
    'Invalid login credentials': 'Correo o contrase침a inv치lidos',
    'User already registered': 'El usuario ya se encuentra registrado',
    'duplicate key value violates unique constraint "unique_contractor_employee"': 'Afectacion duplicada',
    'The resource already exists': 'El recurso ya existe',
    'El recurso ya existe': 'El recurso ya existe',
  };

  if (!errorMessages[error]) {
    //Aqui podemos guardar este error en alguna tabla para poder manejarlo mas adelante
    const supabase = supabaseBrowser();

    const saveErrorMenssage = async () => {
      await supabase.from('handle_errors').insert({
        menssage: error,
        path: window.location.pathname,
      });
    };

    saveErrorMenssage();
  }

  const errorMessage = errorMessages[error] || 'Ha ocurrido un error al procesar la solicitud';
  return errorMessage;
}
